version: '3.8'
services:
  p2p-torrent:
    build: .
    ports:
      - "8080:8080"
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - SIGNAL_PORT=3001
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped