services:
  signaling:
    build: 
      context: ./signaling-server
      dockerfile: Dockerfile
    container_name: signaling-server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - p2p-network

  coturn:
    build: 
      context: ./turn
      dockerfile: Dockerfile
    container_name: coturn
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
      - "49152-65535:49152-65535/udp"
    environment:
      - EXTERNAL_IP=${EXTERNAL_IP:-127.0.0.1}
    restart: unless-stopped
    command: >
      sh -c "sed -i 's/EXTERNAL_IP_PLACEHOLDER/${EXTERNAL_IP:-127.0.0.1}/g' /etc/coturn/turnserver.conf && 
             turnserver -c /etc/coturn/turnserver.conf"
    networks:
      - p2p-network

networks:
  p2p-network:
    driver: bridge