global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'p2p-torrent'
    static_configs:
      - targets: ['p2p-torrent:8080']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s